id: P44CD1B12
initial_creation_type: input
source_metadata:
  title: Turning Back the Summons
  language: bo
  description: 'Texts related to the practice of ‘turning back the summons’ or ‘averting
    the call’ (sun bzlog) of the ḍākinīs:'
  volume:
    877569a133f74347ae8bb8fa5fa896d8:
      title: Brief Turning Back the Summons
      parent: Practices
    ad785e42e9f34ae1a369941259ec35a5:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
created_at: '2022-03-01T06:27:35.577394'
last_modified_at: '2022-03-01T06:27:35.577397'
